Ticket4918 sans dls
ISISComputingGroup/EPICS-LSICorrelator pull request #1
Opened 2020-02-11 14:31 UTC by Alistair-McGann-Tessella

## Description of work:
Adds a PCASpy wrapper around the LSI vendor software

## Ticket:
https://github.com/ISISComputingGroup/IBEX/issues/4918

## Acceptance criteria:
- [ ] LSI software parameters are available as PVs
- [ ] User can start/stop the correlator
- [ ] Correlation function, time lags, trace A and B and metadata saved to a .txt file
     - [ ] These values are made available for use in #4999
- [ ] Device reads disconnected error when the correlator is not connected
- [ ] Driver structure is adequately documented on the wiki

2020-02-28 18:30 UTC, DominicOram requested changes
Generally works but could do with a bit of tidying up, see comments.

2020-02-28 18:30 UTC, DominicOram commented on LSi_Correlator.py
> +sys.path.insert(1, 'C:\\Instrument\\Dev\\LSI-Correlator')
As discussed, we need to think about where the private repository goes on the instrument. Two solutions that come to mind are:
* The code in this repo gets put into the private one and we just use the private one only
* The private repo is a submodule of this repo

2020-02-28 18:30 UTC, DominicOram commented on LSi_Correlator.py
> +sys.path.insert(2, 'C:\\Instrument\\Apps\\EPICS\\ISIS\\inst_servers\\master\\')
Hard coded path, you should be able to use the `EPICS_KIT_ROOT` environment variable.

2020-02-28 18:30 UTC, DominicOram commented on pvdb.py
> +sys.path.insert(1, 'C:\\Instrument\\Dev\\LSI-Correlator')
Same as above, need to find a better home for this.

2020-02-28 18:30 UTC, DominicOram commented on pvdb.py
> +PARAM_FIELDS_BINARY = {'type': 'enum', 'enums': ["NO", "YES"], 'info_field': {'archive': 'VAL', 'INTEREST': 'HIGH'}}
`PARAM_FIELDS_BINARY` is being defined twice

2020-02-28 18:30 UTC, DominicOram commented on pvdb.py
> +from server_common.utilities import char_waveform
`char_waveform` isn't being used

2020-02-28 18:30 UTC, DominicOram commented on pvdb.py
> +    PvNames.LASER_WAVELENGTH: {'type': 'float', 'unit': 'nm', 'info_field': {'archive': 'VAL', 'INTEREST': 'HIGH'}},
These are all basically the same but with different units, worth pulling out into a variable?

2020-02-28 18:30 UTC, DominicOram commented on pvdb.py
> +class PvNames(object):
This should be an ENUM (https://docs.python.org/3.7/library/enum.html)

2020-02-28 18:30 UTC, DominicOram commented on pvdb.py
> +STATIC_PV_DATABASE.update(add_setpoint_pvs(STATIC_PV_DATABASE))
Does everything in `STATIC_PV_DATABASE` need a `SP` equivalent?

2020-02-28 18:30 UTC, DominicOram commented on pvdb.py
> +    return field_database
This seems useful to anything that uses PCASpy, can we put it centrally or better yet get it into pcaspy?

2020-02-28 18:30 UTC, DominicOram commented on LSi_Correlator.py
> +    filepath = ""
Can you change this to have a sensible default (maybe the folder this file is in?) until the macro ticket is done? Just so that it will run without needing changes.

2020-02-28 18:30 UTC, DominicOram commented on LSi_Correlator.py
> +    def __init__(self, pv_prefix, host: str, firmware_revision: str, filepath: str):
`pv_prefix` is unused

2020-02-28 18:30 UTC, DominicOram commented on LSi_Correlator.py
> +        self.PVValues = {
These variables should be snake_case

2020-02-28 18:30 UTC, DominicOram commented on LSi_Correlator.py
> +            print("setting {} to {}".format(pv, preset))
This should be `print_and_log`

2020-02-28 18:30 UTC, DominicOram commented on LSi_Correlator.py
> +            status = Alarm.TIMEOUT_ALARM
This if statement doesn't do anything?

2020-02-28 18:30 UTC, DominicOram commented on LSi_Correlator.py
> +        self.PVValues = {
There are effectively 3 different dictionaries in this object, all very similar:
* SettingsPVs
* PVValues
* pvDB (the one you use through `setParam` and `getParam`)

I think `SettingsPVs` probably needs a better name. I'm not sure I understand the difference between `PVValues` and `pvDB`

2020-02-28 18:30 UTC, DominicOram commented on LSi_Correlator.py
> +            pv_value = self.SettingPVs[reason].convert_to_pv(self.PVValues[reason])
We're calling the convert here in the read and when we do the write in `update_pv_handler`. Does that mean they're going through the converter twice?

2020-02-28 18:30 UTC, DominicOram commented on LSi_Correlator.py
> +        return Corr, Lags, trace_A, trace_B
snake_case please

2020-02-28 18:55 UTC, DominicOram commented
Also, as discussed sending a hex value to a number of the PVs will be converted to floats. e.g. `caput %MYPVPREFIX%:LSICORR_01:SCATTERING_ANGLE:SP b`

2020-03-23 18:57 UTC, DominicOram approved these changes
Looks much better, thanks. Only question is what is the difference between `get_pv_value` and `read`? They seem to be very similar?

2020-03-24 16:21 UTC, Alistair-McGann-Tessella commented
> 
> 
> Looks much better, thanks. Only question is what is the difference between `get_pv_value` and `read`? They seem to be very similar?

They are quite similar, I've changed `get_pv_value` and renamed it to hopefully give the two some distinction

2020-03-25 15:53 UTC, merged