Refactor LSICorrelator as part of handover
ISISComputingGroup/EPICS-LSICorrelator pull request #11
Opened 2021-11-23 11:18 UTC by JamesKingWork

LSICorrelatorVendorInterface:

- Remove unused methods and imports

2021-11-23 13:27 UTC, JackEAllen commented
@JamesKingWork could you add and commit the UML diagram you started in Draw.io and I'll modify it to work with the changes we've made on this so far?

2021-11-23 14:30 UTC, JamesKingWork commented
> @JamesKingWork could you add and commit the UML diagram you started in Draw.io and I'll modify it to work with the changes we've made on this so far?

Added here https://github.com/ISISComputingGroup/EPICS-LSICorrelator/pull/11/commits/9664bdc539a61c85e0dc2b8115976d8890f8dd7a

2021-12-15 13:36 UTC, rerpha requested changes
minor nitpicking, probably not really worth any change unless you really want to, just in future it may be best to just use type hinting in one way and avoid putting it in docstrings as it's more likely to go out of date if in both. 

Other than this i seem to get a unit test failure: 

```
FAIL: test_WHEN_save_data_THEN_metadata_written_AND_correlation_data_written_AND_traces_written (__main__.LSICorrelatorTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests.py", line 110, in test_WHEN_save_data_THEN_metadata_written_AND_correlation_data_written_AND_traces_written
    self.assertEqual(test_actual_data, file.read())
AssertionError: 'Pseudo Cross Correlation\nScattering angl[26064 chars]85\n' != '    Pseudo Cross Correlation\n    Scatter[26136 chars]85\n'
Diff is 26312 characters long. Set self.maxDiff to None to see it.
```
to me it looks like tabs are no longer stripped? 

ioc tests still pass which is good

2021-12-15 13:36 UTC, rerpha commented on correlator_pcaspy.py
> +    @return: None
i'd be tempted to remove the type hint in the comments in favour of the typing in the function signature so there's only one place you need to update it

2021-12-15 13:36 UTC, rerpha commented on correlator_pcaspy.py
> +        @return (str): Filename to save user data to
here as well

2021-12-15 13:36 UTC, rerpha commented on correlator_pcaspy.py
> +        @return (Dict): A dictionary containing meta data to be saved
""

2021-12-15 13:36 UTC, rerpha commented on correlator_pcaspy.py
> +        @return (str): Filename to save archive data to
""

2021-12-15 13:36 UTC, rerpha commented on correlator_pcaspy.py
> +        @return (Any): The value of the PV
""

2021-12-15 13:36 UTC, rerpha commented on correlator_pcaspy.py
> +        @param value (Any): The new value to set the PV to
""

2021-12-15 16:37 UTC, JackEAllen commented
> minor nitpicking, probably not really worth any change unless you really want to, just in future it may be best to just use type hinting in one way and avoid putting it in docstrings as it's more likely to go out of date if in both.
> 
> Other than this i seem to get a unit test failure:
> 
> ```
> FAIL: test_WHEN_save_data_THEN_metadata_written_AND_correlation_data_written_AND_traces_written (__main__.LSICorrelatorTests)
> ----------------------------------------------------------------------
> Traceback (most recent call last):
>   File "tests.py", line 110, in test_WHEN_save_data_THEN_metadata_written_AND_correlation_data_written_AND_traces_written
>     self.assertEqual(test_actual_data, file.read())
> AssertionError: 'Pseudo Cross Correlation\nScattering angl[26064 chars]85\n' != '    Pseudo Cross Correlation\n    Scatter[26136 chars]85\n'
> Diff is 26312 characters long. Set self.maxDiff to None to see it.
> ```
> 
> to me it looks like tabs are no longer stripped?
> 
> ioc tests still pass which is good

I've fixed the unit test now. Was a minor difference in the formatting of the Schema class when placed in the config file compared to the previous implementation.

2021-12-15 16:46 UTC, JackEAllen commented on correlator_pcaspy.py
> +    @return: None
Can I ask what you mean by replacing with function signatures? Could you provide a suggestion somewhere so I can see what you mean? Might move to using it if I think it looks nicer.
All methods include static types and return annotations. 
I decided to include the type hints just out of following a similar docstring format to that of other python projects I've worked on within ISIS for consistency and so the types are visible in intellisense next to the argument descriptions when previewing a method in a given IDE.

2021-12-20 10:13 UTC, rerpha approved these changes

2021-12-20 10:13 UTC, merged