fix minimum time lag stripping, add prec to min time lag
ISISComputingGroup/EPICS-LSICorrelator pull request #15
Opened 2023-01-12 16:16 UTC by rerpha

2023-01-13 13:56 UTC, Tom-Willemsen requested changes
- This causes the existing IOC tests to fail
- Please add IOC tests covering the cases which are fixed by this PR.

2023-01-13 13:56 UTC, Tom-Willemsen commented on correlator_pcaspy.py
> +        min_time_lag_unscaled = self.get_converted_pv_value(Records.MIN_TIME_LAG.name)
Would it be clearer to call this `min_time_lag_ns` or something like that?

2023-01-13 13:56 UTC, Tom-Willemsen commented on correlator_pcaspy.py
> +        min_time_lag = min_time_lag_unscaled / 1e9
magic number

```suggestion
        min_time_lag = min_time_lag_unscaled / NANOSECONDS_TO_SECONDS
```

2023-01-16 11:32 UTC, rerpha commented
> * This causes the existing IOC tests to fail
> * Please add IOC tests covering the cases which are fixed by this PR.

thanks for the review, have addressed comments and added [this PR](https://github.com/ISISComputingGroup/EPICS-IOC_Test_Framework/pull/587) - i think the tests fixed cover the issue so didn't feel i needed to create another one

2023-01-16 14:17 UTC, Tom-Willemsen approved these changes

2023-01-16 14:17 UTC, merged